# Generated by Django 5.2.3 on 2025-06-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('precio_kl', models.DecimalField(decimal_places=2, max_digits=5)),
                ('proveedor', models.CharField(max_length=50)),
            ],
        ),
    ]
