# Generated by Django 5.2.3 on 2025-06-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruta',
            name='precio_kl',
            field=models.IntegerField(),
        ),
    ]
