# Generated by Django 5.2.3 on 2025-06-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad_actual', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=6)),
                ('estado', models.CharField(max_length=10)),
            ],
        ),
    ]
